#Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'